### PR TITLE
Update UI to improve user experience

### PR DESCRIPTION
**Pull request by ebrocas**
The goal of this PR is to propose some adjustments to improve user experience, especially new one who do not know about diffing details. As there is no Quick start on the documentation, I've tried to add as much as possible information in the usage.

This PR contains the following changes:
- rewrite the usage of the CLI
- uniformize options name of the CLI
- add an option to have no output with the CLI expecpt erros
- always save a result file
- if no loader is provided, the CLI will determine the loader to use with the suffix of the files provided
- add colored logs
- progress bars has been moved from the internal API to the CLI. To avoid loading graphical stuff when you only want to manipulate the API
- move `bin/qbindiff` to a `__main__` and create an entry point

Added dependency:
- rich-click

Removed dependency:
- click
- tqdm

usage : 
image

final result:
image

### CODE REVIEW

**Comment by patacca** [comment]
I rebased it on main, reformat the code and changed a few details

**Comment by patacca** [comment]
I rebased it on main, resolving few conflicts

**Comment by RobinDavid** [comment]
Good on my side. @patacca can you proof-test the latest changes before we merge ?

**Comment by patacca** [comment]
I rebased it on the current main and added a few dirty hacks to avoid breaking the inheritance between the two classes `QBinDiff` and `Differ`.

I also took the chance to fix a few small things that went unnoticed.

This also comes with a change in the signature of the `GenericPrePass` and `GenericPostPass` callbacks, that now can optionally return an iterator (from 0 to 1000) that will be used for the progress bar.

**Pull request merged**
